# Generated by Django 3.2.13 on 2022-12-24 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lightchanger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LightPatternOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=1000)),
                ('image', models.URLField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='lightpattern',
            name='light_pattern_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lightchanger.lightpatternoption'),
        ),
    ]
