# Generated by Django 3.2.13 on 2022-12-24 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lightchanger', '0002_auto_20221224_0138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lightpatternoption',
            old_name='image',
            new_name='image_url',
        ),
    ]
