# Generated by Django 4.1.4 on 2023-12-11 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightchanger', '0006_lightpatternoption_parameters_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightpatternoption',
            name='position',
            field=models.IntegerField(default=-1),
        ),
    ]
