# Generated by Django 4.1.4 on 2024-02-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightchanger', '0007_lightpatternoption_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='lightpatternoption',
            name='default_parameters_json',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
