# Generated by Django 4.1.4 on 2024-02-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightchanger', '0009_generatedanimation'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedanimation',
            name='model_response',
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
