# Generated by Django 4.1.4 on 2024-02-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightchanger', '0010_generatedanimation_model_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedanimation',
            name='generated_animation',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='generatedanimation',
            name='model_response',
            field=models.TextField(default=''),
        ),
    ]
