# Generated by Django 4.1.4 on 2024-02-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightchanger', '0012_alter_generatedanimation_generated_animation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedanimation',
            name='parameters_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='generatedanimation',
            name='prompt',
            field=models.TextField(max_length=1000),
        ),
    ]
